#!/usr/bin/env node
// Vendors self-hosted web fonts (from @fontsource packages) and KaTeX assets
// into quartz/, so the published site makes zero third-party requests
// (Google Fonts is blocked and jsDelivr is unreliable in mainland China).
//
// Outputs (committed to the repo):
//   quartz/styles/fonts.css      @font-face rules (latin + latin-ext subsets)
//   quartz/styles/katex.css      katex.min.css with font URLs rewritten
//   quartz/static/fonts/         font files referenced by fonts.css
//   quartz/static/katex-fonts/   KaTeX font files
//
// Font URLs are written relative to the emitted site-root index.css, so they
// work both on GitHub Pages (/BYNotes/) and in local preview.
//
// Usage: npm run vendor-assets   (re-run after bumping @fontsource/* or katex)

import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import path from "node:path"

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const stylesDir = path.join(repoRoot, "quartz", "styles")
const fontsOut = path.join(repoRoot, "quartz", "static", "fonts")
const katexFontsOut = path.join(repoRoot, "quartz", "static", "katex-fonts")
mkdirSync(fontsOut, { recursive: true })
mkdirSync(katexFontsOut, { recursive: true })

// ---- site fonts: mirror what googleFontHref() used to request ----
// header: Schibsted Grotesk 400/700; body: Source Sans Pro 400/600 + italics;
// code: IBM Plex Mono 400/600 (see quartz/util/theme.ts default weights)
const FACES = [
  { pkg: "schibsted-grotesk", css: ["400.css", "700.css"] },
  { pkg: "source-sans-pro", css: ["400.css", "600.css", "400-italic.css", "600-italic.css"] },
  { pkg: "ibm-plex-mono", css: ["400.css", "600.css"] },
]
let fontsCss = "/* generated by scripts/vendor-assets.mjs -- do not edit by hand */\n"
let copied = 0
for (const face of FACES) {
  const pkgDir = path.join(repoRoot, "node_modules", "@fontsource", face.pkg)
  for (const cssFile of face.css) {
    const css = readFileSync(path.join(pkgDir, cssFile), "utf8")
    // fontsource css is a sequence of "/* pkg-subset-weight-style */\n@font-face {...}"
    // blocks; keep only the latin and latin-ext subsets
    const blocks = css.match(/\/\* [\w-]+ \*\/\s*@font-face \{[^}]+\}/g) ?? []
    for (const block of blocks) {
      const descriptor = block.match(/^\/\* ([\w-]+) \*\//)?.[1] ?? ""
      if (!descriptor.startsWith(`${face.pkg}-latin`)) continue
      const rewritten = block.replace(/url\(\.\/files\/([^)]+)\)/g, (_m, file) => {
        copyFileSync(path.join(pkgDir, "files", file), path.join(fontsOut, file))
        copied++
        return `url(static/fonts/${file})`
      })
      fontsCss += rewritten + "\n"
    }
  }
}
writeFileSync(path.join(stylesDir, "fonts.css"), fontsCss)
console.log(`fonts.css written (${copied} font files copied)`)

// ---- KaTeX ----
const katexDist = path.join(repoRoot, "node_modules", "katex", "dist")
const katexVersion = JSON.parse(
  readFileSync(path.join(repoRoot, "node_modules", "katex", "package.json"), "utf8"),
).version
const katexCss = readFileSync(path.join(katexDist, "katex.min.css"), "utf8").replace(
  /url\(fonts\//g,
  "url(static/katex-fonts/",
)
writeFileSync(
  path.join(stylesDir, "katex.css"),
  `/* generated by scripts/vendor-assets.mjs from katex@${katexVersion} katex.min.css -- do not edit */\n` +
    katexCss,
)
let katexCopied = 0
for (const f of readdirSync(path.join(katexDist, "fonts"))) {
  copyFileSync(path.join(katexDist, "fonts", f), path.join(katexFontsOut, f))
  katexCopied++
}
console.log(`katex.css written for katex@${katexVersion} (${katexCopied} katex font files copied)`)
